### Create RSVP
POST http://localhost:5050/rsvps
Content-Type: application/json

{
  "name": "",
  "phone": "",
  "status": "",
  "guests": ,
  "kids": 
}

### List RSVPs
GET http://localhost:5050/rsvps
